In [0]:
import numpy as np

In [0]:
oneD = np.array([1,7,8,9])

In [3]:
oneD

array([1, 7, 8, 9])

In [4]:
type(oneD)

numpy.ndarray

In [5]:
oneD.ndim

1

In [6]:
oneD.shape

(4,)

In [0]:
zeeroD = np.array(100)  # scaler or zeero dimemsional tensor

In [9]:
zeeroD.ndim

0

In [10]:
zeeroD.shape

()

In [0]:
twoD = np.array([[[[[[[[[[[[[[[[[[100]]]]]]]]]]]]]]]]]])

In [12]:
twoD.ndim

18

In [13]:
twoD.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [0]:
twoD2 = np.array([[1,2,3,4],[4,3,2,1],[4,5,6,7]])

In [16]:
twoD2.shape

(3, 4)

In [0]:
scaler >>>>>0D tensor
vector>>>>> 1D tensor
tensor>>>>>>nDtensor

In [0]:
numpy arange function

In [0]:
oneD = np.arange(10)

In [18]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
twoD = np.arange(13).reshape(13,1)

In [20]:
twoD

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [0]:
threeD = np.array([[[1,2,3],[4,5,6],[7,7,8]],[[3,3,3],[4,4,4],[6,6,6]]])

In [22]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 7, 8]],

       [[3, 3, 3],
        [4, 4, 4],
        [6, 6, 6]]])

In [23]:
threeD.shape

(2, 3, 3)

In [0]:
threeD = np.arange(100).reshape(4,5,5)

In [25]:
threeD

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [0]:
#(3,4,2)
ex = np.array([[[1,2],[1,3],[4,5],[6,7]],[[1,2],[1,3],[4,5],[6,7]],[[1,2],[1,3],[4,5],[6,7]]])

In [27]:
ex.shape

(3, 4, 2)

Data type

In [0]:
a = np.array([1.5,2.5,3.6,4.87],dtype = "int32")

In [29]:
a.dtype

dtype('int32')

In [30]:
a

array([1, 2, 3, 4], dtype=int32)

In [0]:
a = np.array([1.5,2.5,3.6,4.87],dtype = np.int8)

In [32]:
a

array([1, 2, 3, 4], dtype=int8)

In [0]:
a= a.astype("float64")

In [34]:
a

array([1., 2., 3., 4.])

In [35]:
aList = [1,2,3,4,5,6,7,8,9]
aList

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
bList = []
for num in aList:
    bList.append(num*5)
bList

[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [0]:
aList  = np.arange(1,21).reshape(4,5)

In [38]:
aList

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
aList *5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [40]:
aList + aList

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [0]:
t1 = np.random.randn(2,3)*10

In [42]:
t1

array([[  6.61273235,   4.66153412, -19.92971522],
       [ -1.42012227,  -8.4358173 ,  16.20339781]])

In [43]:
t2 = np.random.randn(2,3)*100
t2

array([[  36.65266895,  130.10194024, -120.87287115],
       [ -38.45273249,  -53.84406379,   30.68237839]])

In [44]:
t1 + t2

array([[  43.26540129,  134.76347436, -140.80258637],
       [ -39.87285476,  -62.2798811 ,   46.8857762 ]])

In [45]:
t1.shape == t2.shape

True

In [46]:
t1 - t2

array([[ -30.0399366 , -125.44040613,  100.94315593],
       [  37.03261023,   45.40824649,  -14.47898057]])

In [47]:
t1 / t2

array([[0.18041612, 0.03582986, 0.16488162],
       [0.03693163, 0.15667126, 0.5281011 ]])

In [48]:
t1*t2

array([[ 242.3742895 ,  606.47463315, 2408.96190008],
       [  54.60758159,  454.21868508,  497.15878287]])

In [49]:
t1.shape

(2, 3)

In [50]:
t2.shape

(2, 3)

In [0]:
t3 = np.arange(9).reshape(3,3)

In [52]:
t1.shape, t3.shape

((2, 3), (3, 3))

In [53]:
 t3.shape, t1.shapem

((3, 3), (2, 3))

In [54]:
t1@t3

array([[-105.59368898, -114.24913774, -122.9045865 ],
       [  71.91293497,   78.26039322,   84.60785146]])

In [55]:
np.dot(t1,t3)

array([[-105.59368898, -114.24913774, -122.9045865 ],
       [  71.91293497,   78.26039322,   84.60785146]])

In [56]:
t1.dot(t3)

array([[-105.59368898, -114.24913774, -122.9045865 ],
       [  71.91293497,   78.26039322,   84.60785146]])

In [57]:
zeeros = np.zeros((10,10))
zeeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
ones  = np.ones((5,5))*10

In [59]:
ones

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [0]:
fulll = np.full((10,10), 3)

In [61]:
fulll

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [0]:
empty = np.empty((4,4))

In [63]:
empty

array([[2.55930748e-316, 1.01855798e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.10343781e-312, 1.03977794e-312, 1.23075756e-312,
        1.08221785e-312],
       [1.06099790e-312, 9.76118064e-313, 1.16709769e-312,
        1.08221785e-312],
       [1.06099790e-312, 4.44659081e-322, 0.00000000e+000,
        0.00000000e+000]])

In [0]:
eye = np.eye(4,5)

In [65]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [0]:
onesLike = np.ones_like(t1)


In [67]:
onesLike

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
t1

array([[  6.61273235,   4.66153412, -19.92971522],
       [ -1.42012227,  -8.4358173 ,  16.20339781]])

In [69]:
t1>5

array([[ True, False, False],
       [False, False,  True]])

In [70]:
t1[t1<5]

array([  4.66153412, -19.92971522,  -1.42012227,  -8.4358173 ])

Basic Indexing and Slicing

In [0]:
difference?

In [0]:
alist = [1,2,3,4,5,6,7,8,9]

In [72]:
alist[5]

6

In [73]:
type(alist[5])

int

In [74]:
alist[1:5]

[2, 3, 4, 5]

In [75]:
type(alist[5:6])

list

In [76]:
alist[5:6]

[6]

In [0]:
twoD = np.arange(100).reshape(10,10)

In [78]:
twoD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
twoD[5,4]  #

54

In [80]:
twoD[5][4]

54

In [81]:
#twoD[row, column]
#twoD[start:end, start:end]
twoD[3:7,4:7]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [82]:
twoD[8:,4:6]

array([[84, 85],
       [94, 95]])

In [83]:
twoD[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])